export const CONFIG_CONSTANTS = {
  MAX_FETCH_ATTEMPTS: 3,
  RATE_LIMIT_MS: 5000,
  FETCH_TIMEOUT_MS: 10_000,
  SESSION_TIMEOUT_MIN_MS: 30_000,
  SESSION_TIMEOUT_DEFAULT_MS: 15 * 60 * 1000,
} as const;

export type ConfigConstants = typeof CONFIG_CONSTANTS;
