export {
  PII_PATTERNS,
  MAX_CUSTOM_EVENT_NAME_LENGTH,
  MAX_CUSTOM_EVENT_STRING_SIZE,
  MAX_CUSTOM_EVENT_KEYS,
  MAX_CUSTOM_EVENT_ARRAY_SIZE,
  MAX_NESTED_OBJECT_KEYS,
  MAX_METADATA_NESTING_DEPTH,
  MAX_STRING_LENGTH,
  MAX_STRING_LENGTH_IN_ARRAY,
  MAX_ARRAY_LENGTH,
  WEB_VITALS_GOOD_THRESHOLDS,
  WEB_VITALS_NEEDS_IMPROVEMENT_THRESHOLDS,
  WEB_VITALS_POOR_THRESHOLDS,
  DEFAULT_WEB_VITALS_MODE,
  DEFAULT_SESSION_TIMEOUT,
  getWebVitalsThresholds,
} from './constants';

// Backend-only constants - kept for backwards compatibility
// TODO: Move these to their respective backend projects (tracelog-api, tracelog-middleware)
export const ENGAGEMENT_THRESHOLDS = {
  LOW_ACTIVITY_EVENT_COUNT: 50,
  HIGH_ACTIVITY_EVENT_COUNT: 1000,
  MIN_EVENTS_FOR_DYNAMIC_CALCULATION: 100,
  MIN_EVENTS_FOR_TREND_ANALYSIS: 30,
  BOUNCE_RATE_SESSION_THRESHOLD: 1, // Sessions with 1 page view = bounce
  MIN_ENGAGED_SESSION_DURATION_MS: 30 * 1000,
  MIN_SCROLL_DEPTH_ENGAGEMENT: 25, // 25% scroll depth for engagement
} as const;

export const SESSION_ANALYTICS = {
  INACTIVITY_TIMEOUT_MS: 30 * 60 * 1000, // 30min for analytics (vs 15min client)
  SHORT_SESSION_THRESHOLD_MS: 30 * 1000,
  MEDIUM_SESSION_THRESHOLD_MS: 5 * 60 * 1000,
  LONG_SESSION_THRESHOLD_MS: 30 * 60 * 1000,
  MAX_REALISTIC_SESSION_DURATION_MS: 8 * 60 * 60 * 1000, // Filter outliers
  MIN_EVENTS_FOR_DURATION: 2, // Minimum events required to calculate session duration
} as const;

export const INSIGHT_THRESHOLDS = {
  SIGNIFICANT_CHANGE_PERCENT: 20,
  MAJOR_CHANGE_PERCENT: 50,
  MIN_EVENTS_FOR_INSIGHT: 100,
  MIN_SESSIONS_FOR_INSIGHT: 10,
  MIN_CORRELATION_STRENGTH: 0.7, // Strong correlation threshold
  LOW_ERROR_RATE_PERCENT: 1,
  HIGH_ERROR_RATE_PERCENT: 5,
  CRITICAL_ERROR_RATE_PERCENT: 10,
} as const;

export const ANALYTICS_QUERY_LIMITS = {
  DEFAULT_EVENTS_LIMIT: 5,
  DEFAULT_SESSIONS_LIMIT: 5,
  DEFAULT_PAGES_LIMIT: 5,
  MAX_EVENTS_FOR_DEEP_ANALYSIS: 10000,
  MAX_TIME_RANGE_DAYS: 365,
  ANALYTICS_BATCH_SIZE: 1000, // For historical analysis
} as const;

export const SPECIAL_PAGE_URLS = {
  PAGE_URL_EXCLUDED: 'excluded',
  PAGE_URL_UNKNOWN: 'unknown',
} as const;
