name: TraceLog Health Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    # Run daily at 2 AM UTC to catch degradation
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: false
        default: 'development'
        type: choice
        options:
        - development
        - staging
        - production

jobs:
  tracelog-anomaly-detection:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false || github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Unit Tests
        run: |
          echo "🔍 Running unit tests for health check..."
          npm run test:unit

      - name: Run Integration Tests
        run: |
          echo "🔍 Running integration tests for health check..."
          npm run test:integration

      - name: Generate Test Coverage Report
        run: |
          echo "🔍 Generating test coverage report for health check..."
          npm run test:coverage

      - name: Build TraceLog library
        run: npm run build:all

      - name: Run TraceLog Health Analysis
        id: health-check
        run: |
          echo "Running comprehensive TraceLog health analysis..."
          npm run ci:health-check > health-output.txt 2>&1
          echo "exit_code=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Upload Health Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tracelog-health-report-node${{ matrix.node-version }}
          path: |
            test-reports/anomaly-report.json
            health-output.txt
            coverage/
          retention-days: 30

      - name: Comment PR with Health Status
        if: github.event_name == 'pull_request' && steps.health-check.outputs.exit_code != '0'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## ⚠️ TraceLog Health Check

            The health analysis detected issues that require attention.

            ### Test Results
            ✅ Unit tests passed
            ✅ Integration tests passed
            ✅ Test coverage generated
            ⚠️ Health analysis found concerns

            📄 [Download full health report from artifacts](../actions/runs/${{ github.run_id }})
            📊 [Test coverage included in artifacts](../actions/runs/${{ github.run_id }})

            Please review the health report before merging.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Fail on Health Issues
        if: steps.health-check.outputs.exit_code != '0'
        run: |
          echo "❌ TraceLog health check failed"
          echo "🔍 Check the health report for details"
          exit 1

  notify-teams:
    runs-on: ubuntu-latest
    needs: tracelog-anomaly-detection
    if: failure() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Notify Teams on Critical Failure
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: |
            🚨 **TraceLog Health Check Failed**

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            Critical TraceLog library issues detected!
            Check the workflow logs for details.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}